export default {
  base: 'https://open-api.10ss.net',
  authorize: '/oauth/authorize',
  accessToken: '/oauth/oauth',
  refreshToken: '/oauth/oauth',
  addMachineAuth: '/printer/addprinter',
  delMachineAuth: '/printer/deleteprinter',
  menuCreate: '/printmenu/addprintmenu',
  shutdownRestart: '/printer/shutdownrestart',
  printIndex: '/print/index',
  voice: '/printer/setsound',
  printInfo: '/printer/printinfo',
  version: '/printer/getversion',
  cancelAllPrint: '/printer/cancelall',
  cancelOnePrint: '/printer/cancelone',
  setLogo: '/printer/seticon',
  removeLogo: '/printer/deleteicon',
  order: '/printer/getorder',
  btnPrint: '/printer/btnprint',
}
